services:
  backend:
    build:
      context: ./backend
    image: renefondufe/zuri-backend:latest
    ports:
      - '5000:5000'
    env_file:
      - ./backend/.env.example
    volumes:
      - ./backend/src:/usr/src/app/src

  frontend:
    build:
      context: ./frontend
    image: renefondufe/zuri-frontend:latest
    ports:
      - '3000:80'
    depends_on:
      - backend
